### ISSUE TITLE
USB path

### ISSUE THREAD

**Issue by imranrazakhan** [keithy/ign-embed#1]
In your script you expect USB at /dev/sdb1, what if USB is not available on this path, I experienced similar issue while installing CentOS. There should be more dynamic way to identify USB.

**Comment by keithy** [comment]
Sure, I am open to suggestions.

**Comment by keithy** [comment]
Added brute force attempts to mount /dev/sdb1 /dev/sdc1 and /dev/sdd1 just in case. (only one of these will succeed)
